### ISSUE TITLE
real-data testset seems to be missing

### ISSUE THREAD

**Issue by frednam93** [boschresearch/acoustic-traffic-simulation-counting#1]
Hi!

I am trying to replicate this repository and I am stuck at model inference. when I try to run atsc.counting.inference, it seems that I need "test" split of dataset for the real-data but when I downloaded the real-data from zenodo, it does not have test split. Is there certain way you made test split from existing dataset on Zenodo or the dataset is uploaded without test split?

Thanks!

Regards,
Hyeonuk Nam

**Comment by luca-bondi** [comment]
Hi @frednam93, test data will be released on June 1st, as per https://dcase.community/challenge2024/index

If you want to run the inference step on validation data that is already available you can either:
- use Hydra override, e.g., `poetry run python -m atsc.counting.inference site=<locX> inference.alias=finetune inference.split=val`
- replace `test` with `val` in https://github.com/boschresearch/acoustic-traffic-simulation-counting/blob/f45b5dac701e2147d86eca1ea2a3381d4c9a6e47/atsc/configs/baseline.yaml#L123

**Comment by frednam93** [comment]
Thanks! Then are the [results on DCASE task description page](https://dcase.community/challenge2024/task-acoustic-based-traffic-monitoring#evaluation-and-ranking) is based on validation split?
